default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("POSTGRES_DB") { "ecommerce_app" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "ecommerce_app" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "ecommerce_app" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "ecommerce_app" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "ecommerce_app" } %>_production
